<?php
  $lang['number']		= 'Contrato';
  $lang['date']			= 'Fecha';
  $lang['due']			= 'Facha de vencimiento';
  $lang['to']			= 'Facturación a';
  $lang['from']			= 'Nuestra información ';
  $lang['product']		= 'Producto';
  $lang['qty']			= 'Cantidad';
  $lang['price']		= 'Precio';
  $lang['discount']		= 'Descuento';
  $lang['vat']			= 'Impuestos';
  $lang['total']		= 'Total';
  $lang['page']			= 'Página';
  $lang['page_of']		= 'de';
  $lang['time']		= 'fecha';
?>